const div = document.getElementById('container');
div.style.backgroundColor = "yellow";
div.style.color = "blue";
div.style.margin = "20px";
div.style.padding = "20px";
div.style.fontSize = "18px";
div.style.fontWeight = "bold";
div.style.height = "200px";
div.style.width = "300px";